max-97/pse

- .gitignore
- Pflichtenheft/01_Einleitung.tex
- Pflichtenheft/02_Zielbestimmung.tex
- Pflichtenheft/03_Produkteinsatz.tex
- Pflichtenheft/04_Produktumgebung.tex
- Pflichtenheft/05_FunktionaleAnforderungen.tex
- Pflichtenheft/06_Produktdaten.tex
- Pflichtenheft/07_NichtfunkAnforderungen.tex
- Pflichtenheft/08_Benutzungsoberflaeche.tex
- Pflichtenheft/09_Qualitaetsbestimmungen.tex
- Pflichtenheft/10_Systemmodelle.tex
- Pflichtenheft/11_TestfaelleSzenarien.tex
- Pflichtenheft/12_Glossar.tex
- Pflichtenheft/master.tex
Jedes Kapitel bekommt seine eigene .tex. Formatierung und zusammenfügen der Kapitel in master.tex.
> Initiale Datein für Pflichtenheft

- Pflichtenheft/02_Zielbestimmung.tex
- Pflichtenheft/05_FunktionaleAnforderungen.tex
Vorest fertige Version der Zielbestimmung, die Kommentare kann man entfernen wenn es übernommen wurde. Die Punkte unter _Ablauf der Simulation_ wurden entfernt, weil sie zu funktionalen Anforderungen gehören.
> Zielbestimmung

- Pflichtenheft/05_FunktionaleAnforderungen.tex
TODOS:
- Referenzen auf funktionale Anforderungen evtl. updaten
- Produktdaten um gespeicherte Spiele, Strategien und Initialisierungen erweitern
- Systemmodelle updaten
- Benutzeroberfläche updaten
- Glossar updaten. Definition von Konfiguration, Initialisierung und reicher, ärmer, ungefähr gleich reich (vlg. Änderungen)
- Szenarien updaten und neue hinzufügen (Spiele, Strategien erstellen und speichern)
> Funktionale Anforderungen überarbeitet

- Pflichtenheft/02_Zielbestimmung.tex
- Pflichtenheft/05_FunktionaleAnforderungen.tex
- Pflichtenheft/12_Glossar.tex
- Pflichtenheft/master.tex
Änderungen sind in der PDF rot markiert.
> Aenderung anforderungen

- Implementierung/src/main/java/de/sswis/view/model/VMCombinedStrategy.java
- Implementierung/src/main/java/de/sswis/view/model/VMConfiguration.java
- Implementierung/src/main/java/de/sswis/view/model/VMGame.java
- Implementierung/src/main/java/de/sswis/view/model/VMGroup.java
- Implementierung/src/main/java/de/sswis/view/model/VMInitialization.java
- Implementierung/src/main/java/de/sswis/view/model/VMResult.java
- Implementierung/src/main/java/de/sswis/view/model/VMStrategy.java
Hinzufügen einiger Getter und Setter Methoden. Werden zum Implementieren anderer Klassen benötigt.
> Getter und Setter für ViewModel

- Implementierung/src/main/java/de/sswis/model/CombinedStrategy.java
- Implementierung/src/main/java/de/sswis/model/MixedStrategy.java
Testklassen schreib ich separat, da Agent und History implementiert sein sollten.
> CombinedStrategy und MixedStrategy Implementierung

- Implementierung/src/main/java/de/sswis/model/Agent.java
- Implementierung/src/main/java/de/sswis/model/algorithms/pairing/RandomPairing.java
Durch das mergen war ausversehen eine Methode doppelt in Agent.java und bei einem Algorithmus hat getName() gefehlt.
> Kleine Fehler behoben

- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/RankPercentage.java
- Implementierung/src/test/java/de/sswis/model/algorithms/adaptation/RankPercentageTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicRankTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicScoreTest.java
Ich fix die Fehler in den Testklassen der Algorithmen die aufgrund der Standardkonstruktoren enstehen nach diesem Merge.
> Adaptationalgorithms Tests

- Implementierung/src/main/java/de/sswis/view/CustomComponents/CombinedStrategyTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/CombinedStrategyTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/ConfigurationTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/GameTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/GameTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/GroupTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/InitializationTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/InitializationTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/MixedStrategyTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/MixedStrategyTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/ResultTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/ResultTab.java
- Implementierung/src/main/java/de/sswis/view/MainView.form
- Implementierung/src/main/java/de/sswis/view/MainView.java
- Implementierung/src/main/java/de/sswis/view/ManageCombinedStrategiesView.java
- Implementierung/src/main/java/de/sswis/view/ManageConfigurationsView.java
- Implementierung/src/main/java/de/sswis/view/ManageGamesView.java
- Implementierung/src/main/java/de/sswis/view/ManageInitializationsView.java
- Implementierung/src/main/java/de/sswis/view/ManageResultsView.java
- Implementierung/src/main/java/de/sswis/view/ManageStrategiesView.java
- Implementierung/src/main/java/de/sswis/view/NewCombinedStrategyView.form
- Implementierung/src/main/java/de/sswis/view/NewCombinedStrategyView.java
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.java
- Implementierung/src/main/java/de/sswis/view/NewStrategyView.form
- Implementierung/src/main/java/de/sswis/view/NewStrategyView.java
Hab ein paar Fehler in der view behoben... folgendes sollte damit jetzt funktionieren:
-hinzufügen und entfernen von kombinierten Strategien-/ Bedingungen-Zeilen in NewCombinedStrategyView und NewStrategyView
-DropDownMenüs von DefaultStrategy in NewCombinedStrategyView und von allen Parametern in NewConfigurationView sollten die entsprechenden Listeneinträge anzeigen
-In den Manage*Views sollten jetzt die korrekten Werte der VMObjekte abgebildet werden (vorrausgesetzt sie wurden korrekt gespeichert)
> View fixes

- Implementierung/src/main/java/de/sswis/controller/Sswis.java
- Implementierung/src/main/java/de/sswis/controller/handlers/EditCombinedStrategyHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/EditConfigurationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewCombinedStrategyHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewCombinedStrategyViewHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewConfigurationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewConfigurationViewHandler.java
- Implementierung/src/main/java/de/sswis/view/AbstractNewCombinedStrategyView.java
- Implementierung/src/main/java/de/sswis/view/AbstractNewConfigurationView.java
- Implementierung/src/main/java/de/sswis/view/NewCombinedStrategyView.java
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.java
- Implementierung/src/main/java/de/sswis/view/model/VMCombinedStrategy.java
- Implementierung/src/main/java/de/sswis/view/model/VMConfiguration.java
Die Namen der Parameter der Algorithmen und Conditions werden jetzt in die NewConfigurationView bzw. NewCombinedStrategyView geschrieben. Die VMConfiguration bzw. VMCombinedStrategy haben Attribute zum Speichern der Parameter bekommen.
> Algorithm paramters

- Implementierung/src/main/java/de/sswis/controller/ModelParser.java
- Implementierung/src/main/java/de/sswis/view/model/VMCombinedStrategy.java
Parameterdarstellung in VMCombinedStrategy gefixt.
> Conditions haben jetzt beliebige Parameter

- Implementierung/src/main/java/de/sswis/model/Initialization.java
- Implementierung/src/main/java/de/sswis/model/Simulation.java
- Implementierung/src/main/java/de/sswis/model/algorithms/ranking/AverageRank.java
- Implementierung/src/main/java/de/sswis/model/algorithms/ranking/CurrentCycleScore.java
- Implementierung/src/main/java/de/sswis/model/algorithms/ranking/CustomCycleScore.java
- Implementierung/src/main/java/de/sswis/model/algorithms/ranking/RankingAlgorithm.java
- Implementierung/src/main/java/de/sswis/model/algorithms/ranking/Score.java
Startkapital kann jetzt in den Bewertungsalgorithmen ignoriert werden.
> Startkapital nur für Strategien

- Implementierung/src/main/java/de/sswis/model/strategies/GrimIndividual.java
> getName hat liefert nicht mehr null zurück

- Implementierung/src/main/java/de/sswis/controller/ModelParser.java
- Implementierung/src/main/java/de/sswis/model/Configuration.java
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.form
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.java
- Implementierung/src/main/java/de/sswis/view/model/VMConfiguration.java
- Implementierung/src/test/java/de/sswis/controller/ModelProviderTest.java
- Implementierung/src/test/java/de/sswis/model/SimulationTest.java
Der Gleichgewichtszustand kann jetzt vom Benutzer definiert werden. Muss noch in der Simulation entsprechend geprüft werden.
> Configuration Equilibrium

- Implementierung/src/main/java/de/sswis/controller/ModelParser.java
- Implementierung/src/main/java/de/sswis/controller/handlers/EditInitializationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewInitializationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewInitializationViewHandler.java
- Implementierung/src/main/java/de/sswis/view/AbstractNewInitializationView.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/GroupTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/GroupTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/InitialStrategyTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/InitialStrategyTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/InitializationTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/StartCapitalTab.form
- Implementierung/src/main/java/de/sswis/view/CustomComponents/StartCapitalTab.java
- Implementierung/src/main/java/de/sswis/view/NewCombinedStrategyView.java
- Implementierung/src/main/java/de/sswis/view/NewInitializationView.java
- Implementierung/src/main/java/de/sswis/view/model/VMInitialization.java
Attribute von VMinitialization richtig gesetzt
VMInitialization wird in der GUI korrekt angezeigt
+ Buttons zum Hinzufügen von initialen Strategien und Startkapital
> Initialization fixes

- Implementierung/src/main/java/de/sswis/model/History.java
- Implementierung/src/main/java/de/sswis/model/Simulation.java
> Multithreading in Simulation

- Implementierung/src/main/java/de/sswis/model/Simulation.java
Ranking nur noch am Ende jedes Zyklus wie im Pflichtenheft beschrieben
> Ranking nicht mehr jede Runde

- Implementierung/src/main/java/de/sswis/view/ShowResultView.java
Chart zur Darstellung der durschnittlichen Punktzahl pro Zyklus
> Durschnittliche Punktzahl

- Implementierung/src/main/java/de/sswis/view/ManageCombinedStrategiesView.java
- Implementierung/src/main/java/de/sswis/view/ManageConfigurationsView.java
- Implementierung/src/main/java/de/sswis/view/ManageGamesView.java
- Implementierung/src/main/java/de/sswis/view/ManageInitializationsView.java
- Implementierung/src/main/java/de/sswis/view/ManageResultsView.java
- Implementierung/src/main/java/de/sswis/view/ManageStrategiesView.java
> GUI Fenster passen jetzt ihre Größe an den Inhalt an

- Implementierung/src/main/java/de/sswis/controller/handlers/EditConfigurationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewConfigurationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/NewConfigurationViewHandler.java
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.java
> Parameter für neue Konfigurationen werden jetzt korrekt abgefragt

- Implementierung/src/main/java/de/sswis/util/DataSetHelper.java
- Implementierung/src/main/java/de/sswis/view/NewCombinedStrategyView.java
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.java
fixes #146 
Negative Punktzahlen können in der Ergebnisansicht angezeigt werden
und zusätzliche Parameter werden auch beim editieren geladen
> Result view bug fix

- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/MixedLinearInterpolation.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/MixedSum.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/RankPercentage.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicRank.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicScore.java
Bei gleichem Namen findet keine Anpassung mehr statt
> Adaptation Fix

- Implementierung/src/main/java/de/sswis/view/CustomComponents/GroupTab.java
> Initialisierung ohne Startkapital nun erlaubt

- Implementierung/src/main/java/de/sswis/model/Agent.java
- Implementierung/src/main/java/de/sswis/model/Game.java
- Implementierung/src/main/java/de/sswis/model/History.java
- Implementierung/src/main/java/de/sswis/model/Initialization.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/MixedLinearInterpolation.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/MixedSum.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/RankPercentage.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicRank.java
- Implementierung/src/main/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicScore.java
- Implementierung/src/main/java/de/sswis/model/algorithms/pairing/RandomPairing.java
- Implementierung/src/main/java/de/sswis/model/algorithms/ranking/AverageRank.java
- Implementierung/src/main/java/de/sswis/model/strategies/AlwaysCooperate.java
- Implementierung/src/main/java/de/sswis/model/strategies/GrimEverybody.java
- Implementierung/src/main/java/de/sswis/model/strategies/GrimIndividual.java
- Implementierung/src/main/java/de/sswis/model/strategies/GroupGrim.java
- Implementierung/src/main/java/de/sswis/model/strategies/GroupTitForTat.java
- Implementierung/src/main/java/de/sswis/model/strategies/NeverCooperate.java
- Implementierung/src/main/java/de/sswis/model/strategies/Random.java
- Implementierung/src/main/java/de/sswis/model/strategies/TitForTatEverybody.java
- Implementierung/src/main/java/de/sswis/model/strategies/TitForTatIndividual.java
- Implementierung/src/test/java/de/sswis/model/ConditionsTest.java
- Implementierung/src/test/java/de/sswis/model/SimulationTest.java
- Implementierung/src/test/java/de/sswis/model/StrategiesTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/ConditionsTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/adaptation/ReplicatorDynamicScoreTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/pairing/BruteForcePairingHeuristicTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/pairing/BruteForcePairingTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/pairing/MinimumWeightMatchingTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/ranking/AverageRankTest.java
- Implementierung/src/test/java/de/sswis/model/algorithms/ranking/ScoreTest.java
> Model Test Coverage

- Implementierung/src/main/java/de/sswis/controller/FileManager.java
- Implementierung/src/main/java/de/sswis/controller/ModelParser.java
- Implementierung/src/main/java/de/sswis/controller/MultiViewNotifier.java
- Implementierung/src/main/java/de/sswis/controller/Sswis.java
- Implementierung/src/main/java/de/sswis/controller/ViewNotifier.java
- Implementierung/src/main/java/de/sswis/controller/handlers/ManageResultsHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/SaveResultsHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/ShowResultsHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/StartSimulationHandler.java
- Implementierung/src/main/java/de/sswis/controller/handlers/StopSimulationHandler.java
- Implementierung/src/main/java/de/sswis/util/InputValidator.java
- Implementierung/src/main/java/de/sswis/view/AbstractMainView.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/GroupTab.java
- Implementierung/src/main/java/de/sswis/view/CustomComponents/ResultTabs/MultiResultTab.java
- Implementierung/src/main/java/de/sswis/view/MainView.java
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.form
- Implementierung/src/main/java/de/sswis/view/NewConfigurationView.java
- Implementierung/src/main/java/de/sswis/view/NewGameView.java
- Implementierung/src/main/java/de/sswis/view/NewInitializationView.java
- Implementierung/src/main/java/de/sswis/view/ShowMultiResultView.java
- Implementierung/src/main/java/de/sswis/view/ShowResultView.java
- Implementierung/src/main/java/de/sswis/view/model/VMConfiguration.java
- Implementierung/src/main/java/de/sswis/view/model/VMGroup.java
- Implementierung/src/main/java/de/sswis/view/model/VMInitialization.java
- Implementierung/src/test/java/de/sswis/controller/ModelParserTest.java
Fixes #152 
Ergebnisse sollten jetzt korrekt geladen werden. Außerdem noch einige Fehler bei der Multikonfiguration behoben, die mir währenddessen aufgefallen sind.
Ich hatte noch keine Zeit es zu testen!!
> Laden von Ergebnissen
